### ISSUE TITLE
"Error in gzfile(file, mode) : all connections are in use" in "epitopes::get_proteins" step

### ISSUE THREAD

**Issue by CuypersBart** [fcampelo/epitopes#12]
Following the tutorial, in the "epitopes::get_proteins" step, and "epitopes::get_taxonomy" step, I get the error:

"Error in gzfile(file, mode) : all connections are in use"

Do you know what might be causing the error?

**Comment by fcampelo** [comment]
Hi @CuypersBart ,

would you be able to provide a minimal reproducible example so that I can check it here? It would also be helpful if you mention your OS and the R version you're running.

Cheers,
Felipe

**Comment by CuypersBart** [comment]
Dear Felipe,

I followed exactly your example and am not sure what is going on (https://fcampelo.github.io/epitopes/articles/Usage-example.html). The only thing I changed is the folder names. 

Please see the code here:

![image](https://user-images.githubusercontent.com/9530810/150308102-c0c2e304-9bab-43b4-a6ca-a8827ae12ca0.png)

R version is 4.1.2

![image](https://user-images.githubusercontent.com/9530810/150308386-847194c1-ac6b-4ac4-86a5-725f940fe365.png)

OS is Windows 11 Pro (built 22000).
The computer was freshly installed and has 8 physical cores and 32 GB of RAM.

**Comment by fcampelo** [comment]
This is weird, as the point at which it throws the error - the end of `get_proteins()` - shouldn't require any call to `gzfile()`. I got myself a windows laptop here and I'll try to reproduce your error.

**Comment by CuypersBart** [comment]
Thank you for checking!

It is indeed weird. 
As you can see in the screenshot, also running the command "installed.packages()" throws the error after, but not before running your tool. 

It looks like it is opening some connections, but not properly closing them?

**Comment by fcampelo** [comment]
Tried to reproduce the error on a Windows machine here (Win 10, 16GB RAM, 8 cores, R 4.1.2), but found a different error - this one probably related to memory overflow, likely due to a single massive XML file that's part of the IEDB export. Curious thing is that it never happens either Linux or Mac OS. 

I'm currently working on the next version of the package, which doesn't suffer from this problem (well-tested on all three OS), but in the meantime I've run the extraction routines on my side and uploaded their resulting data sets to <https://github.com/fcampelo/epitopes/tree/master/data> (the epitopes data is already in there, proteins and taxonomy will follow as soon as they finish running here) so that you can bypass the data retrieval step. 

I hope that helps.

Best,
Felipe
